# Use Python 3.9 as base image
FROM python:3.9-slim-buster

# Set the working directory
WORKDIR /app

ENV MY_ENV_VAR2=my_value_101

# Copy the requirements.txt file
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the source code
COPY app.py app.py

# Expose the port that the application listens on
EXPOSE 8080

# Start the application
CMD ["python", "app.py"]
